services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./Api/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always  

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_URL=http://api:5555
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    restart: always  